### ISSUE TITLE
Run<bool, bool> Async

### ISSUE THREAD

**Issue by rakkarage** [NVentimiglia/Unity3d-Async-Task#3]
it seems like Run is async but "Run(bool, bool) is not? is this a bug or am i doing something wrong? thanks

	using Foundation.Tasks;
	using UnityEngine;
	public class TestTask : MonoBehaviour
	{
	    [ContextMenu("Work0")]
	    public void Work0()
	    {
	        // works, animation continues
	        UnityTask.Run(RealWork).ContinueWith(t => Debug.Log("Done!"));
	    }
	    [ContextMenu("Work1")]
	    public void Work1()
	    {
	        // does not work. animation freezes
	        UnityTask<bool>.Run<bool, bool>(RealWork, false).ContinueWith(t => Debug.Log("Done! " + t.Result));
	    }
	    private bool RealWork(bool test)
	    {
	        RealWork();
	        return test;
	    }
	    private void RealWork()
	    {
	        const int count = 100;
	        for (var y = 0; y < count; y++)
	        {
	            for (var x = 0; x < count; x++)
	            {
	                Debug.Log(new Vector2(x, y));
	            }
	        }
	    }
	}

**Comment by NVentimiglia** [comment]
Thanks for the test. Always nice to have a second pair of eyes.

It looked ok on my end and then I added a UnityTasks.Wait(1000) to the mix. It did lock up my UI. I looked into the code and discovered I was running on the main thread (for no good reason) in that specific case. 

Please redownload to release 5-26

**Comment by rakkarage** [comment]
thanks :)
